Constrain the torch version due to installation issues
Currently, torch version 1.13.0 causes installation to fail on ARM Mac devices.
Error: `Unable to find installation candidates for nvidia-cudnn-cu11 (8.5.0.96)`